#数据库连接，屏蔽的可直接加序号改名字==弃用。
#数据库连接用户schema, 不管底层物理数据库是否集群分布还是云啥的，这里实际是单用户可见的数据库。
app:
  datasource:
    #源程序中@ConfigurationProperties(prefix="app.datasource.sei")和这里名字要一致。
    #若没有Oracle可用，本机可使用H2数据库测试就行。　可能要修改Hibernate中配置数据库方言设置。
    sei:
      url: jdbc:h2:tcp://localhost/~/sei2
      username: sa
      password:
    sei4:
      url: jdbc:oracle:thin:@//192.168.104.34:1521/fjtj
      username: fjseiinuser
      password: fjseiuser12345678
    #监察等其它的数据库。每一个用户数据库都独立配置。JPA一次Query无法跨越多个数据库,当然上层的逻辑代码可以支持任意数量数据库。
    #若没有开启本机H2的console，将会自动使用H2内存数据库。
    #旧平台正式运行的。
    fjtj4:
      url: jdbc:oracle:thin:@//192.168.168.6:1521/fjtj
      username: fjseiinuser
      password: fjseiuser12345678
    fjtj:
      url: jdbc:h2:tcp://localhost/~/fjtj
      username: sa
      password:
    #监察数据库。
    incp6:
      url: jdbc:h2:tcp://localhost/~/incp
      username: sa
      password:
    sdn7:
      url: jdbc:h2:tcp://localhost/~/sdn
      username: sa
      password:


trace: false
debug: true
#监控信息，生产环境要权限或者控制
management:
  endpoint:
    #shutdown.enabled: true 宕机
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: heapdump,env

server:
  port: 8673
  undertow:
    io-threads: 2
    worker-threads: 12
    buffer-size: 512
    direct-buffers: true
  ssl:
    #对https,http的协议切换
    enabled: false
    #生成证书的名字
    key-store: SeiYewu.keystore
    #密钥库密码
    key-store-password: 123456
    key-store-type: JKS
    key-alias: SeiYewu

graphql:
  servlet:
    #缺省模型改成低级权限要求的，而Subscription的servlet也用缺省模型。
    mapping: /public
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
    tracing-enabled: true
    actuator-metrics: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION

logging:
  file:
    path: E:\\del\\logs
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com:
      oembedler:
        moon:
          graphql:
            boot:
              error: debug


jwt:
  header: Authorization
  expiration: 5400
  secret: df1jgV0jh56Oje8DrtOrn9E1df0l0g94ns

unibackend:
  tools:
    #自带缺省的模型开关
    starter-enabled: true
    third-enabled: true
    main-enabled: true

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  application:
    name: unibackend
  profiles:
    active:
    - product
  jta:
    atomikos:
      properties:
        #没效果? 要去jta.properties文件
        #default-jta-timeout: 2600000
        #max-timeout: 30000000
        enable-logging: true
  #log-dir: classpath:newlog
  #transaction-manager-id: txManager
  jpa:
    properties:
      javax:
        persistence:
          sharedCache.mode: ENABLE_SELECTIVE
      #开启查询缓存factory_class    cache.use_query_cache: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate:
        javax:
          cache:
            missing_cache_strategy: create
        #default_schema: newsei   还是一个个指定好
        #看SQL打印　true 　false
        show_sql: true
        #统计对单个hibernate session会话的总结
        generate_statistics: true
        ##      dialect: org.hibernate.dialect.Oracle10gDialect
        hbm2ddl:
          auto: update
        #替换缓存provider
        cache:
          redisson:
            Fast:
              expiration:
                time_to_live: 99000
                #max_idle_time: 27000
          #二级缓存关闭启用的2个总开关,关不了集合字段
          use_second_level_cache: true
          use_query_cache: true
          region:
            #非商业收费版本只能用最差那一个SingletonRedisRegionFactory。分开Hibernate版本RedissonRegionFactory
            factory_class: org.redisson.hibernate.RedissonRegionFactory
    generate-ddl: true
    open-in-view: true
  main:
    allow-bean-definition-overriding: true
  mvc:
  cache:


  #graphql.playground:    # false
  #   editor.fontFamily: "'Source Code Pro','Monaco', monospace"
  #  responses:
  #  - classpath:exampleResponse1.json
  #  - classpath:variables.json

file:
  #上传文件root,在此上扩展子目录,不带F:就是当前程序运行盘的。
  upload-dir: F:/Users/uploads

sei:
  visibility:
    #ROLE_USER graphql模型文件中没@authr(qx明确指的将用的角色缺省值,仅针对主安全域graphql设置的。
    role:
  testMode: true
  control:
    #若PermitAnyURL false true 那么：不登录REST就能随意访问，但是graphQL没变化。
    permitAnyURL: true
  cache.log: false
  server.URI: http://192.168.1.105:8673
  cookie:
    domain: 192.168.1.105
  filter:
    #浏览器用Access-Control-Max-Age
    maxage: 3600
    #允许接入cors前端各服务器地址
    origin:
      map[https://27.151.117.65:3765]:
      map[http://27.151.117.65:3765]:
      map[https://localhost:3765]:
      map[http://localhost:3765]:
      map[https://192.168.171.3:3765]:
      map[http://192.168.171.3:3765]:
      map[https://192.168.1.105:3765]:
      map[http://192.168.1.105:3765]:
      map[http://localhost:3764]:
      map[http://192.168.1.105:3764]:
      map[http://localhost:3000]:
      map[http://localhost:3100]:
      map[http://192.168.171.3:3000]:
